name: Build

on:
  push:
    tags: [ '*' ]

jobs:
  build-linux-x86_64:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: build-launcher
      run: |
        make -C launcher clean all

    - run: |
        mvn --batch-mode -DskipTests package

    - uses: softprops/action-gh-release@v2
      with:
        files: |
          target/propeller-firmware-loader-*

  build-linux-aarch64:
    runs-on: ubuntu-22.04-arm

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: build-launcher
      run: |
        make -C launcher clean all

    - run: |
        mvn --batch-mode -DskipTests package

    - uses: softprops/action-gh-release@v2
      with:
        files: |
          target/propeller-firmware-loader-*

  build-windows-x86_64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - run: |
        mvn --batch-mode -DskipTests package

    - uses: softprops/action-gh-release@v2
      with:
        files: |
          target/propeller-firmware-loader-*

  build-macos-x86_64:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - run: |
        mvn --batch-mode -DskipTests package

    - uses: softprops/action-gh-release@v2
      with:
        files: |
          target/propeller-firmware-loader-*

  build-macos-aarch64:
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - run: |
        mvn --batch-mode -DskipTests package

    - uses: softprops/action-gh-release@v2
      with:
        files: |
          target/propeller-firmware-loader-*
